sudo: required

dist: trusty

language: generic

cache:
  directories:
    - /home/travis/.ccache
    - /home/travis/.cache/pip
    - /home/travis/.ros/data

env:
  global:
    - ADDITIONAL_DEBS='build-essential python-catkin-tools python-pip'
    - DOCKER_IMAGE=ros:indigo-ros-core
    - DOCKER_RUN_OPTS='-v /home/travis:/root'
    - ROSINSTALL_FILENAME=.travis.rosinstall
    - UPSTREAM_WORKSPACE=file
    - ROSDEP_INSTALL_OPTS='-q --ignore-src -r'
  matrix:
    - ROS_DISTRO=indigo

install:
  - git clone https://github.com/wkentaro/industrial_ci.git .ci_config -b rosdep_install_opts
script:
  # build & test ROS packages
  - .ci_config/travis.sh
  # build doc
  - cd $TRAVIS_BUILD_DIR/doc
  - unset PYTHONPATH  # cleanup for virtualenv
  - source setup.sh
  - make html

notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
