sudo: false
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro  USE_JENKINS=true NO_SUDO=true ROSWS=wstool BUILDER=catkin USE_DEB=true
  - ROS_DISTRO=indigo                  NO_SUDO=true ROSWS=wstool BUILDER=catkin USE_DEB=true
script: source .travis/travis.sh
before_script:
  - export ROS_PARALLEL_JOBS="-j2 -l2"
notifications:
  email:
    on_success: always
    on_failure: always
