language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin   USE_DEB=true
  - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin   USE_DEB=true
matrix:
  allow_failures:
    - env: ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin   USE_DEB=true
script: source .travis/travis.sh
before_script:
  - export ROS_PARALLEL_JOBS="-j8"
notifications:
  email:
    on_success: always
    on_failure: always
