language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin   USE_DEB=true
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin   USE_DEB=false
  - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin   USE_DEB=true
  - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin   USE_DEB=false
matrix:
  allow_failures:
    - env: ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin   USE_DEB=true
    - env: ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin   USE_DEB=false
    - env: ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin   USE_DEB=false
script: source .travis/travis.sh
before_script:
  - export ROS_PARALLEL_JOBS="-j2 -l2"
after_failure:
  - rosrun roseus generate-all-msg-srv.sh --all
  - rostest jsk_2014_picking_challenge test_robot_motion.test
notifications:
  email:
    on_success: always
    on_failure: always
