sudo: false

language: generic

env:
  global:
    - BUILDER=catkin
    - NO_SUDO=true
    - NOT_TEST_INSTALL=true
    - USE_DEB=true
    - ROS_PARALLEL_JOBS="-j8"
    - ROSWS=wstool
    - ROSDEP_ADDITIONAL_OPTIONS="-q -n --ignore-src"
    - BEFORE_SCRIPT='sudo pip install -U git+https://github.com/catkin/catkin_tools.git@bfed3ab4216c11f167d572d54e8560c4756479fd'
  matrix:
    - ROS_DISTRO=indigo

script:
  # build & test ROS packages
  - source .travis/travis.sh
  # build doc
  - cd $TRAVIS_BUILD_DIR/doc
  - unset PYTHONPATH  # cleanup for virtualenv
  - source setup.sh
  - make html

notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
