sudo: required
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  global:
    - ROSWS=wstool
    - BUILDER=catkin
    - USE_DEB=true
    - USE_TRAVIS=true
    - ROS_PARALLEL_JOBS="-j8"
  matrix:
    - ROS_DISTRO=indigo
    - ROS_DISTRO=jade
services:
  - docker
matrix:
  allow_failures:
    - env: ROS_DISTRO=jade
before_script:
  # prepare rosbag for test
  - wget https://raw.githubusercontent.com/Nanolx/patchimage/master/tools/gdown.pl -O jsk_2015_05_baxter_apc/test/gdown.pl  # script to download large file from Google Drive
  - (cd jsk_2015_05_baxter_apc/test/; perl gdown.pl 'https://drive.google.com/uc?id=0B9P1L--7Wd2vTkdoUXAzdnVobWc' 2015-10-07-10-20-12_bin-box-array.bag)
script: source .travis/travis.sh
notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
