sudo: required

dist: trusty

language: generic

cache:
  directories:
    - $HOME/.ccache
    - $HOME/.cache/pip
    - $HOME/.ros/data

env:
  global:
    - CATKIN_TOOLS_CONFIG_OPTIONS="--blacklist imagesift jsk_recognition_msgs jsk_perception jsk_pcl_ros_utils jsk_pcl_ros resized_image_transport checkerboard_detector"
    - NOT_TEST_INSTALL=true
    - ROS_PARALLEL_JOBS="-j2"
    - ROSDEP_ADDITIONAL_OPTIONS="-n -v --ignore-src --skip-keys=jsk_smart_gui --skip-keys=ros3djs --skip-keys=pr2_calibration_launch --skip-keys=jsk_android_gui_api9 --skip-keys=ros2djs --skip-keys=face_recognition --skip-keys=roslibjs --skip-keys=force_proximity_ros --skip-keys=safe_teleop_base"
    - USE_DEB=false
    - USE_TRAVIS=true
  matrix:
    - ROS_DISTRO=indigo

install:
  - git clone https://github.com/jsk-ros-pkg/jsk_travis.git .travis
  - (cd .travis && git checkout 40640d45c709bdc7d74a1f8983d51d5df553dbc1)
  # FIXME: https://github.com/start-jsk/jsk_apc/issues/2281
  - sudo -H apt-get install -qq -y python-setuptools
  - sudo -H easy_install -q -U pip
  - sudo -H pip install -q -U pip setuptools
  - sudo -H pip install -U gdown

script:
  # build & test ROS packages
  - source .travis/travis.sh
  # build doc
  - cd $TRAVIS_BUILD_DIR/doc
  - unset PYTHONPATH  # cleanup for virtualenv
  - source setup.sh
  - make html

notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
